# Generated by Django 5.1.11 on 2025-06-27 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_image', models.ImageField(blank=True, null=True, upload_to='weapons/')),
                ('weapon_type', models.CharField(choices=[('magic', 'Magic'), ('melee', 'Melee'), ('ranged', 'Ranged')], default='melee', max_length=10)),
                ('strength_needed', models.IntegerField()),
                ('intelligence_needed', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('inventory', models.TextField()),
                ('equipment', models.TextField()),
                ('backstory', models.TextField()),
                ('appearance', models.TextField()),
                ('personality', models.TextField()),
                ('alignment', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('luck', models.IntegerField()),
                ('skills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.weapon')),
            ],
        ),
    ]
